name: ci
on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=23
      - run: cmake --build build -j
      - run: ctest --test-dir build --output-on-failure

  perf_gate:
    runs-on: ubuntu-22.04
    env:
      PERF_BUDGET_NS: '150000'   # 150 µs
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=23
      - run: cmake --build build -j
      - name: run bench and check budget
        run: |
          set -e
          # Run the bench; keep full table in logs
          out="$(./build/bench_update | tee /dev/stderr)"

          # Parse the first data row's ns/op column from nanobench's table.
          # The header contains "ns/op", followed by a separator row, then the data row.
          avg_ns="$(printf '%s\n' "$out" \
            | awk -F'|' '/ns\/op/{getline; gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2; exit}')"

          # Fallback if parsing failed
          if [ -z "$avg_ns" ]; then
            echo "Failed to parse ns/op from nanobench output"
            exit 2
          fi

          echo "avg_ns=$avg_ns ns/op"
          echo "budget=${PERF_BUDGET_NS} ns/op"

          # Numeric compare (handles floats) using awk
          awk -v x="$avg_ns" -v b="$PERF_BUDGET_NS" 'BEGIN { exit !(x < b) }'
  tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM 17 + clang-tidy-17
        run: |
          set -eux
          curl -fsSL https://apt.llvm.org/llvm.sh -o llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
          # <-- llvm.sh doesn't install clang-tidy by default; install it explicitly
          sudo apt-get update
          sudo apt-get install -y clang-tidy-17
          clang-tidy-17 --version

      - run: sudo apt-get update && sudo apt-get install -y ninja-build jq

      - run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - run: cmake --build build -j

      - name: run clang-tidy (src/include only; fail on issues)
        run: |
          set -e
          files=$(jq -r '.[].file' build/compile_commands.json \
            | awk -v root="$GITHUB_WORKSPACE" 'index($0, root"/src/")==1 || index($0, root"/include/")==1' \
            | grep -E '\.(c|cc|cpp|cxx|h|hpp)$' | sort -u)
          [ -z "$files" ] && exit 0
          clang-tidy-17 -p build --warnings-as-errors='*' $files
  werror:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=23 -DCEX_WERROR=ON
      - run: cmake --build build -j
asan_ubsan:
  name: ASan/UBSan
  runs-on: ubuntu-latest
  timeout-minutes: 20
  steps:
    - uses: actions/checkout@v4
    - name: Configure (RelWithDebInfo + sanitizers)
      run: cmake -S . -B build-asan -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSANITIZE_KIND=asan_ubsan
    - name: Build
      run: cmake --build build-asan -j
    - name: Test (ctest)
      env:
        ASAN_OPTIONS: abort_on_error=1:strict_string_checks=1:check_initialization_order=1
        UBSAN_OPTIONS: print_stacktrace=1:abort_on_error=1
        ASAN_SYMBOLIZER_PATH: llvm-symbolizer
      run: ctest --test-dir build-asan --output-on-failure

tsan:
  name: TSan
  runs-on: ubuntu-latest
  timeout-minutes: 25
  steps:
    - uses: actions/checkout@v4
    - name: Configure (RelWithDebInfo + TSan)
      run: cmake -S . -B build-tsan -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSANITIZE_KIND=tsan
    - name: Build
      run: cmake --build build-tsan -j
    - name: Test (ctest)
      env:
        TSAN_OPTIONS: history_size=7 suppressions=scripts/tsan.supp
      run: ctest --test-dir build-tsan --output-on-failure


